### ISSUE TITLE
Code Table 4.2-0-19: add new codes for freezing levels

### ISSUE THREAD

**Issue by edouardsandrine** [wmo-im/GRIB2#278]
### Initial request

Hi WMO TT-TDCF Task Team,

We would like to encode freezing levels for aviation people, CMAC operational forecasters (production of GFAs), avalanche program, and all the external users interested in this parameter.

Thanks a lot for your attention.

### Amendment details

Currently, we can only find the highest freezing level in the table [table 4.2-0-19](https://github.com/wmo-im/GRIB2/blob/master/GRIB2_CodeFlag_4_2_0_19_CodeTable_en.csv), we would like to encode all freezing levels and not only the highest one (that could be encoded using the freezing level code).

I assume we can not replace the current parameter by another one for all freezing levels since it might be already used by a lot of users... So, could we add another one less specific following:

| Parameter                                     | Product Discipline | Parameter Category | Parameter number | Units |
|-----------------------------------------------|--------------------|--------------------|------------------|-------|
| Freezing level height                  | 0| 19:physical atmospheric properties|52 | m     |

### Requestor(s)

Sandrine Edouard, @edouardsandrine , CCMEP, ECCC

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 0, category 19

### Expected impact of change

None

**Comment by sebvi** [comment]
Dear @edouardsandrine ,

this is an interesting proposal. However, I don't see what you are going to use in the encoding of the first and second fixed surfaces. If my understanding is correct, you are also planning to encode several freezing levels.

if it is the case, I would suggest to create an entry "freezing level" in code Table 4.5 (maybe entry 28?) so that you can use it in your first/second fixed surfaces. You can then use the scale factor/scaled values of the surfaces to index your freezing levels and eventually define a layer between 2 freezing levels if that's useful.

**Comment by edouardsandrine** [comment]
Thanks a lot @sebvi , that's sound good ! I 

I hadn't thought of this table, but you're right, it makes a lot of sense.

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-tdcf/wiki/2024.11.13.tt.tdcf notes:
- Sandrine introduced the proposal
- Sebastien adding to table 4.5 as well "freezing level" (without height); looks like
Fixed surface types and units |   | 4 |   | Level of 0 °C isotherm might be enough... @sebvi will consult with colleagues

**Comment by edouardsandrine** [comment]
@sebvi , did you receive any comment form your colleagues ? Thanks a lot!

**Comment by amilan17** [comment]
https://github.com/wmo-im/et-data/wiki/2024.12.03.et.data notes:
still waiting for feedback from @sebvi 
- Matthew will reach out to NEMO for comments from NEMO before 20 December.

**Comment by sebvi** [comment]
> @sebvi , did you receive any comments from your colleagues ? Thanks a lot!

after consulting with colleagues, we believe that we could use the "Level of 0 °C isotherm" to encode the freezing levels.

**Comment by amilan17** [comment]
https://github.com/wmo-im/et-data/wiki/2025.01.14.et.data notes:
@edouardsandrine will update the proposal (based on feedback) and update the branch

**Comment by edouardsandrine** [comment]
From what I understood I should request for a new input to the [table 4.5](https://github.com/wmo-im/GRIB2/blob/master/GRIB2_CodeFlag_4_5_CodeTable_en.csv) according to:

| Title_en                                     | SubTitle_en | CodeFlag | Value | MeaningParameterDescription_en |
|---------------------------------- |-------------|------------------|------------|------------------|
| Fixed surface types and units    |                 | 28                |       | Freezing level      |

Do you want me to update the title as well as the main request at the top of this issue accordingly ?

Many thanks for your patience.

**Comment by amilan17** [comment]
@edouardsandrine yes, please update the title as well.

**Comment by edouardsandrine** [comment]
Done! Thanks

**Comment by edouardsandrine** [comment]
I tried to push the branch but it failed...

```
Traceback (most recent call last):
  File "/home/runner/work/GRIB2/GRIB2/scripts/create_master_lists.py", line 186, in <module>
    process_files(template_files,"GRIB2_Template",writers,"Identification template")
  File "/home/runner/work/GRIB2/GRIB2/scripts/create_master_lists.py", line 146, in process_files
    writer.write_row(row)            
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/GRIB2/GRIB2/scripts/create_master_lists.py", line 27, in write_row
    self.csvwriter.writerow(row)
  File "/usr/lib/python3.12/csv.py", line 164, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'OctetCount'
Error: Process completed with exit code 1.
```

Can't find what's wrong in my update of the table 4.5.. 

Can someone help me please ?

Really sorry about that...

**Comment by amilan17** [comment]
@edouardsandrine it looks like you successfully pushed a commit to the branch two hours ago. The error message is due to the XML generation failure and Antoine is working on a fix for this in a separate branch. 
Therefore, I think that you did everything right unless there something else you are trying to do.

**Comment by amilan17** [comment]
> > [@sebvi](https://github.com/sebvi) , did you receive any comments from your colleagues ? Thanks a lot!
> 
> after consulting with colleagues, we believe that we could use the "Level of 0 °C isotherm" to encode the freezing levels.

@edouardsandrine @sebvi 
I'm confused. If I understand correctly, Sebastien recommends using 
**Fixed surface types and units,,4,,Level of 0 °C isotherm,,,-,Operational** 
instead of adding a new code 
**Fixed surface types and units,,28,,Freezing level,,,m,Operational**

**Comment by edouardsandrine** [comment]
Yes, you are right. Sorry for the confusion. So no branch to update , right ?

Thanks for your patience...

**Comment by amilan17** [comment]
yes, and I'll remove this proposal from the amendments. Thanks for confirming.
